.TH CAT 1 2022-07-02 Ferass'\ Base\ System.
.SH NAME
cat \- concatenate files to stdout
.SH SYNOPSIS
.B cat
.RB [ \-u ]
.RB [ FILE ] ...
.SH DESCRIPTION
Concatenate files to standard output (stdout).
.P
With no file or when file is -, read and concatenate standard input 
to standard output.
.TP
.B -u
Print unbuffered.
.P
.SH EXAMPLES
.TP
.B cat foobar
Output foobar's contents to standard output.
.TP
.B cat
Output standard input to standard output.
.TP
.B cat -u hello.c
Output hello.c's contents unbuffered to standard output. 
.TP
.B cat foo bar baz
Output foo's contents, then bar's, then baz's to standard output.
.SH AUTHOR
Originally written by Ferass EL HAFIDI as part of the fases 
project \- Ferass' Base System. Part of the code is written by 
Leah Rowe.
.P
Source code is at http://git.vitali64.duckdns.org/utils/fases.git.
.SH COPYRIGHT
.P
Copyright (C) 2022 Ferass EL HAFIDI
.P
Copyright (C) 2022 Leah Rowe
