.TH DIRNAME 1 2022-10-07 Ferass'\ Base\ System.
.SH NAME
dirname \- Return directory portion of a pathname
.SH SYNOPSIS
.B dirname
.RB < STRING >
.SH DESCRIPTION
Return directory portion of the STRING pathname.
.SH EXAMPLES
.TP
.B dirname /bin/sh
Return directory portion ("/bin/").
.SH AUTHOR
Written by Ferass EL HAFIDI as part of the fases 
project \- Ferass' Base System.
.P
Source code is at http://git.vitali64.duckdns.org/utils/fases.git.
.SH COPYRIGHT
.P
Copyright (C) 2022 Ferass EL HAFIDI
