.TH ECHO 1 2022-07-02 Ferass'\ Base\ System.
.SH NAME
echo \- Write a string to standard output
.SH SYNOPSIS
.B echo
.RB [ STRING ] ...
.SH DESCRIPTION
Write a string to standard output (stdout).
.SH EXAMPLES
.TP
.B echo foobar
Output the string "foobar" to standard output.
.TP
.B echo foo bar baz
Output the string "foo bar baz" to standard output.
.SH AUTHOR
Written by Ferass EL HAFIDI as part of the fases 
project \- Ferass' Base System.
.P
Source code is at http://git.vitali64.duckdns.org/utils/fases.git.
.SH COPYRIGHT
.P
Copyright (C) 2022 Ferass EL HAFIDI
