.TH TRUE 1 2022-07-02 Ferass'\ Base\ System.
.SH NAME
true \- Return true value
.SH SYNOPSIS
.B true
.SH DESCRIPTION
Return true value.
.SH AUTHOR
Written by Ferass EL HAFIDI as part of the fases 
project \- Ferass' Base System.
.P
Source code is at http://git.vitali64.duckdns.org/utils/fases.git.
.SH COPYRIGHT
.P
Copyright (C) 2022 Ferass EL HAFIDI
