.TH CAT(1)
.SH NAME
cat \- print file contents to stdout
.SH SYNOPSIS
.B cat
.RB [ --help ] [ FILE ]
.SH DESCRIPTION
Concatenate FILE to standard output (stdout).
.P
With no FILE, read standard input (stdin).
.P
.B --help
Print a help message and exit.
.P
.SH EXAMPLES
.B cat foobar
Output foobar's content to standard output.
.P
.B cat
Output standard input to standard output.
.SH AUTHOR
Written by Ferass EL HAFIDI as part of the fases 
project \- Ferass' Base System.
.SH COPYRIGHT
Copyright (C) 2022 Ferass EL HAFIDI.
